#!/usr/bin/env bash
# 根据 deploy.conf 生成 .env.hybrid（cloud2 节点）
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/load-deploy-conf.sh"

TARGET="${1:-${APP_ROOT_LIGHT2:-}/.env.hybrid}"
NODE="${2:-cloud2}"

prompt_if_empty DB_PASS "PostgreSQL 密码 (DB_PASS)" true
prompt_if_empty REDIS_PASS "Redis 密码 (REDIS_PASS)" true
prompt_if_empty COS_SECRET_ID "COS SecretId (CAM 子账号)" true
prompt_if_empty COS_SECRET_KEY "COS SecretKey" true
prompt_if_empty ADMIN_PASSWORD "后台管理员密码 (ADMIN_PASSWORD)" true

[[ -n "${SECRET_KEY:-}" ]] || SECRET_KEY="$(gen_secret)"
[[ -n "${JWT_SECRET_KEY:-}" ]] || JWT_SECRET_KEY="$(gen_secret)"

LIGHT1="${LIGHT1_IP:?请设置 LIGHT1_IP}"
LIGHT2="${LIGHT2_IP:?请设置 LIGHT2_IP}"
COS_EP="${COS_ENDPOINT:-cos.ap-beijing.myqcloud.com}"
COS_BKT="${COS_BUCKET:-tk-monitor888-1333628464}"

if [[ "$NODE" == "cloud2" ]]; then
  COMPUTE_NODE_ID=cloud2
  COMPUTE_NODE_LABEL="轻量云 #2"
  BEAT_ENABLED_ON_NODE=true
  CELERY_WORKER_NODE_PREFIX=cloud2
  CELERY_WORKER_CONCURRENCY=10
  CLUSTER_PEER="http://${LIGHT2}:8000"
else
  COMPUTE_NODE_ID=local
  COMPUTE_NODE_LABEL="本地电脑"
  BEAT_ENABLED_ON_NODE=false
  CELERY_WORKER_NODE_PREFIX=local
  CELERY_WORKER_CONCURRENCY=24
  CLUSTER_PEER="http://${LIGHT2}:8000"
fi

if [[ "$NODE" == "cloud2" ]]; then
  CLUSTER_PEER=""
fi

mkdir -p "$(dirname "$TARGET")"
cat >"$TARGET" <<EOF
LOCAL_MODE=false
SERVE_FRONTEND=true
APP_ENV=production
DEBUG=false

SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440

DATA_DIR=data
ENABLE_API_DOCS=false

DATABASE_URL=postgresql+asyncpg://tiktok_monitor:${DB_PASS}@${LIGHT1}:5432/tiktok_monitor
DATABASE_URL_SYNC=postgresql://tiktok_monitor:${DB_PASS}@${LIGHT1}:5432/tiktok_monitor
REDIS_URL=redis://:${REDIS_PASS}@${LIGHT1}:6379/0
PROXY_POOL_REDIS_DB=1

MINIO_ENDPOINT=${COS_EP}
MINIO_ACCESS_KEY=${COS_SECRET_ID}
MINIO_SECRET_KEY=${COS_SECRET_KEY}
MINIO_BUCKET=${COS_BKT}
MINIO_SECURE=true

COMPUTE_NODE_ID=${COMPUTE_NODE_ID}
COMPUTE_NODE_LABEL="${COMPUTE_NODE_LABEL}"
BEAT_ENABLED_ON_NODE=${BEAT_ENABLED_ON_NODE}
CELERY_WORKER_NODE_PREFIX=${CELERY_WORKER_NODE_PREFIX}
CLUSTER_PEER_API_URL=${CLUSTER_PEER}
CLUSTER_EXPECTED_WORKERS_LOCAL=24
CLUSTER_EXPECTED_WORKERS_CLOUD2=10
CLUSTER_NODE_LABEL_LOCAL="本地电脑"
CLUSTER_NODE_LABEL_CLOUD2="轻量云 #2"

CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY}
API_UVICORN_WORKERS=2
POSTGRES_BACKUP_ENABLED=false
WEB_DEPLOY_UPDATE_ENABLED=true

SNAPSHOT_RETENTION_DAYS=90
SNAPSHOT_PURGE_BATCH_SIZE=5000
POSTGRES_BACKUP_KEEP_LOCAL=7
POSTGRES_BACKUP_KEEP_REMOTE=14
POSTGRES_BACKUP_BUCKET_PREFIX=backups/postgres

SCRAPE_ALLOW_MOCK=false
SCRAPE_INTERVAL_MINUTES=1440
SCRAPE_REQUEST_DELAY_MIN=5
SCRAPE_REQUEST_DELAY_MAX=12
SCRAPE_MAX_RETRIES=3
SCRAPE_RETRY_INTERVAL_MINUTES=5

PROXY_POOL_ENABLED=true
PROXY_POOL_HEALTH_URL=https://www.tiktok.com
PROXY_POOL_BAD_TTL_SECONDS=1800
PROXY_POOL_MAX_FAIL_STREAK=3
PROXY_POOL_LOCAL_ENV_FALLBACK=false

SINGBOX_ENABLED=true
SINGBOX_BIN=data/bin/sing-box
PROXY_GATEWAY_BASE_PORT=18080

DOUBAO_ENABLED=true
ARK_API_KEY=${ARK_API_KEY:-your-ark-api-key-here}
ARK_BASE_URL=https://ark.cn-beijing.volces.com/api/v3
ARK_MODEL=doubao-1-5-vision-pro-32k-250115
RECOGNITION_AUTO_TRIGGER=false

TMDB_API_KEY=${TMDB_API_KEY:-your-tmdb-api-key-here}
BANGUMI_ENABLED=true
BANGUMI_ACCESS_TOKEN=
BANGUMI_USER_AGENT=tiktok-monitor/1.0

ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
EOF

chmod 600 "$TARGET"
echo ">> 已生成 $TARGET (节点: $NODE)"
